databases:
  - name: ksleep-db
    databaseName: ksleep_db
    user: ksleep_user
    plan: free
    region: singapore

services:
  - type: web
    name: ksleep-ecommerce
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: ksleep-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ksleep-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ksleep-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ksleep-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ksleep-db
          property: password
      - key: SPRING_MAIL_HOST
        value: in-v3.mailjet.com
      - key: SPRING_MAIL_PORT
        value: "587"
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
